// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using The_Daily_Travel_Log;

namespace The_Daily_Travel_Log.Migrations
{
    [DbContext(typeof(LocationDataContext))]
    [Migration("20221116234911_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("The_Daily_Travel_Log.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentCountry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentDateAndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStateOrProvince")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentTown")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
